version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE-KAFKA:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"
  
  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
